### ISSUE TITLE
Unable to dial number in outbound

### ISSUE THREAD

**Issue by Pradhyo** [TwilioDevEd/clicktocall-flask#12]
First time using Twilio.

This code did not work:
```
with response.dial() as dial:
    dial.number("+16518675309")
```

This worked in the end:
`response.dial("+16518675309")`

I couldn't find docs easily for VoiceResponse(), most examples just show `response.say()`.
`response.dial("+16518675309")` was a lucky guess based on error `TypeError: dial() takes at least 2 arguments (1 given)`

**Comment by smendes** [comment]
Thank you for your message. Indeed this comment was wrong, it was using the previous version of the twilio-python library. It is now updated.
