### ISSUE TITLE
link seems to be broken (ngrok)

### ISSUE THREAD

**Issue by LotharSchubert** [TwilioDevEd/clicktocall-flask#15]
In Step 5 "Expose your application to the wider internet using ngrok. You can click here for more details.", the hyperlink under "ngrok" (https://github.com/TwilioDevEd/clicktocall-flask#expose-the-application-to-the-wider-internet) seems not to lead anywhere.

**Comment by po5i** [comment]
Sorry for the late response. The ngrok link is just an example of how it would look like after you start your ngrok tunnel. The ngrok CLI will tell you the actual link that is available to your environment.
